export enum MongoCollections {
  'USER' = 'user',
  'ROLE' = 'role',
  'COMPANY' = 'company',
  'DEVICE' = 'device',
  'LOG' = 'logs',
  'HISTORY' = 'history',
  'MAINTENANCE' = 'maintenance',
  'OPERATOR' = 'operator',
  'OPERATOR_ASSIGNMENT' = 'operator-assignment',
  'OPERATOR_PLANNING' = 'shift-planning',
  'OPERATOR_MOVEMENT' = 'operator-movement',
  'STOP' = 'stop',
  'REPORT' = 'report',
  'REPORT_TEMPLATE' = 'report-template',
  'ALARM' = 'alarm',
  'CLAIM' = 'claim',
  'TYPE' = 'type',
  'DETECTION' = 'detection',
}
