import { KeywordType, PaginationType } from './repository/global.repository';

export enum TimeZone {
  'Pacific/Niue' = 'Pacific/Niue',
  'Pacific/Pago_Pago' = 'Pacific/Pago_Pago',
  'Pacific/Honolulu' = 'Pacific/Honolulu',
  'Pacific/Rarotonga' = 'Pacific/Rarotonga',
  'Pacific/Tahiti' = 'Pacific/Tahiti',
  'Pacific/Marquesas' = 'Pacific/Marquesas',
  'America/Anchorage' = 'America/Anchorage',
  'Pacific/Gambier' = 'Pacific/Gambier',
  'America/Los_Angeles' = 'America/Los_Angeles',
  'America/Tijuana' = 'America/Tijuana',
  'America/Vancouver' = 'America/Vancouver',
  'America/Whitehorse' = 'America/Whitehorse',
  'Pacific/Pitcairn' = 'Pacific/Pitcairn',
  'America/Denver' = 'America/Denver',
  'America/Phoenix' = 'America/Phoenix',
  'America/Mazatlan' = 'America/Mazatlan',
  'America/Dawson_Creek' = 'America/Dawson_Creek',
  'America/Edmonton' = 'America/Edmonton',
  'America/Hermosillo' = 'America/Hermosillo',
  'America/Yellowknife' = 'America/Yellowknife',
  'America/Belize' = 'America/Belize',
  'America/Chicago' = 'America/Chicago',
  'America/Mexico_City' = 'America/Mexico_City',
  'America/Regina' = 'America/Regina',
  'America/Tegucigalpa' = 'America/Tegucigalpa',
  'America/Winnipeg' = 'America/Winnipeg',
  'America/Costa_Rica' = 'America/Costa_Rica',
  'America/El_Salvador' = 'America/El_Salvador',
  'Pacific/Galapagos' = 'Pacific/Galapagos',
  'America/Guatemala' = 'America/Guatemala',
  'America/Managua' = 'America/Managua',
  'America/Cancun' = 'America/Cancun',
  'America/Bogota' = 'America/Bogota',
  'Pacific/Easter' = 'Pacific/Easter',
  'America/New_York' = 'America/New_York',
  'America/Iqaluit' = 'America/Iqaluit',
  'America/Toronto' = 'America/Toronto',
  'America/Guayaquil' = 'America/Guayaquil',
  'America/Havana' = 'America/Havana',
  'America/Jamaica' = 'America/Jamaica',
  'America/Lima' = 'America/Lima',
  'America/Nassau' = 'America/Nassau',
  'America/Panama' = 'America/Panama',
  'America/Port-au-Prince' = 'America/Port-au-Prince',
  'America/Rio_Branco' = 'America/Rio_Branco',
  'America/Halifax' = 'America/Halifax',
  'America/Barbados' = 'America/Barbados',
  'Atlantic/Bermuda' = 'Atlantic/Bermuda',
  'America/Boa_Vista' = 'America/Boa_Vista',
  'America/Caracas' = 'America/Caracas',
  'America/Curacao' = 'America/Curacao',
  'America/Grand_Turk' = 'America/Grand_Turk',
  'America/Guyana' = 'America/Guyana',
  'America/La_Paz' = 'America/La_Paz',
  'America/Manaus' = 'America/Manaus',
  'America/Martinique' = 'America/Martinique',
  'America/Port_of_Spain' = 'America/Port_of_Spain',
  'America/Porto_Velho' = 'America/Porto_Velho',
  'America/Puerto_Rico' = 'America/Puerto_Rico',
  'America/Santo_Domingo' = 'America/Santo_Domingo',
  'America/Thule' = 'America/Thule',
  'America/St_Johns' = 'America/St_Johns',
  'America/Araguaina' = 'America/Araguaina',
  'America/Asuncion' = 'America/Asuncion',
  'America/Belem' = 'America/Belem',
  'America/Argentina/Buenos_Aires' = 'America/Argentina/Buenos_Aires',
  'America/Campo_Grande' = 'America/Campo_Grande',
  'America/Cayenne' = 'America/Cayenne',
  'America/Cuiaba' = 'America/Cuiaba',
  'America/Fortaleza' = 'America/Fortaleza',
  'America/Godthab' = 'America/Godthab',
  'America/Maceio' = 'America/Maceio',
  'America/Miquelon' = 'America/Miquelon',
  'America/Montevideo' = 'America/Montevideo',
  'Antarctica/Palmer' = 'Antarctica/Palmer',
  'America/Paramaribo' = 'America/Paramaribo',
  'America/Punta_Arenas' = 'America/Punta_Arenas',
  'America/Recife' = 'America/Recife',
  'Antarctica/Rothera' = 'Antarctica/Rothera',
  'America/Bahia' = 'America/Bahia',
  'America/Santiago' = 'America/Santiago',
  'Atlantic/Stanley' = 'Atlantic/Stanley',
  'America/Noronha' = 'America/Noronha',
  'America/Sao_Paulo' = 'America/Sao_Paulo',
  'Atlantic/South_Georgia' = 'Atlantic/South_Georgia',
  'Atlantic/Azores' = 'Atlantic/Azores',
  'Atlantic/Cape_Verde' = 'Atlantic/Cape_Verde',
  'America/Scoresbysund' = 'America/Scoresbysund',
  'Africa/Abidjan' = 'Africa/Abidjan',
  'Africa/Accra' = 'Africa/Accra',
  'Africa/Bissau' = 'Africa/Bissau',
  'Atlantic/Canary' = 'Atlantic/Canary',
  'Africa/Casablanca' = 'Africa/Casablanca',
  'America/Danmarkshavn' = 'America/Danmarkshavn',
  'Europe/Dublin' = 'Europe/Dublin',
  'Africa/El_Aaiun' = 'Africa/El_Aaiun',
  'Atlantic/Faroe' = 'Atlantic/Faroe',
  'Etc/GMT' = 'Etc/GMT',
  'Europe/Lisbon' = 'Europe/Lisbon',
  'Europe/London' = 'Europe/London',
  'Africa/Monrovia' = 'Africa/Monrovia',
  'Atlantic/Reykjavik' = 'Atlantic/Reykjavik',
  'Africa/Algiers' = 'Africa/Algiers',
  'Europe/Amsterdam' = 'Europe/Amsterdam',
  'Europe/Andorra' = 'Europe/Andorra',
  'Europe/Berlin' = 'Europe/Berlin',
  'Europe/Brussels' = 'Europe/Brussels',
  'Europe/Budapest' = 'Europe/Budapest',
  'Europe/Belgrade' = 'Europe/Belgrade',
  'Europe/Prague' = 'Europe/Prague',
  'Africa/Ceuta' = 'Africa/Ceuta',
  'Europe/Copenhagen' = 'Europe/Copenhagen',
  'Europe/Gibraltar' = 'Europe/Gibraltar',
  'Africa/Lagos' = 'Africa/Lagos',
  'Europe/Luxembourg' = 'Europe/Luxembourg',
  'Europe/Madrid' = 'Europe/Madrid',
  'Europe/Malta' = 'Europe/Malta',
  'Europe/Monaco' = 'Europe/Monaco',
  'Africa/Ndjamena' = 'Africa/Ndjamena',
  'Europe/Oslo' = 'Europe/Oslo',
  'Europe/Paris' = 'Europe/Paris',
  'Europe/Rome' = 'Europe/Rome',
  'Europe/Stockholm' = 'Europe/Stockholm',
  'Europe/Tirane' = 'Europe/Tirane',
  'Africa/Tunis' = 'Africa/Tunis',
  'Europe/Vienna' = 'Europe/Vienna',
  'Europe/Warsaw' = 'Europe/Warsaw',
  'Europe/Zurich' = 'Europe/Zurich',
  'Asia/Amman' = 'Asia/Amman',
  'Europe/Athens' = 'Europe/Athens',
  'Asia/Beirut' = 'Asia/Beirut',
  'Europe/Bucharest' = 'Europe/Bucharest',
  'Africa/Cairo' = 'Africa/Cairo',
  'Europe/Chisinau' = 'Europe/Chisinau',
  'Asia/Damascus' = 'Asia/Damascus',
  'Asia/Gaza' = 'Asia/Gaza',
  'Europe/Helsinki' = 'Europe/Helsinki',
  'Asia/Jerusalem' = 'Asia/Jerusalem',
  'Africa/Johannesburg' = 'Africa/Johannesburg',
  'Africa/Khartoum' = 'Africa/Khartoum',
  'Europe/Kiev' = 'Europe/Kiev',
  'Africa/Maputo' = 'Africa/Maputo',
  'Europe/Kaliningrad' = 'Europe/Kaliningrad',
  'Asia/Nicosia' = 'Asia/Nicosia',
  'Europe/Riga' = 'Europe/Riga',
  'Europe/Sofia' = 'Europe/Sofia',
  'Europe/Tallinn' = 'Europe/Tallinn',
  'Africa/Tripoli' = 'Africa/Tripoli',
  'Europe/Vilnius' = 'Europe/Vilnius',
  'Africa/Windhoek' = 'Africa/Windhoek',
  'Asia/Baghdad' = 'Asia/Baghdad',
  'Europe/Istanbul' = 'Europe/Istanbul',
  'Europe/Minsk' = 'Europe/Minsk',
  'Europe/Moscow' = 'Europe/Moscow',
  'Africa/Nairobi' = 'Africa/Nairobi',
  'Asia/Qatar' = 'Asia/Qatar',
  'Asia/Riyadh' = 'Asia/Riyadh',
  'Antarctica/Syowa' = 'Antarctica/Syowa',
  'Asia/Tehran' = 'Asia/Tehran',
  'Asia/Baku' = 'Asia/Baku',
  'Asia/Dubai' = 'Asia/Dubai',
  'Indian/Mahe' = 'Indian/Mahe',
  'Indian/Mauritius' = 'Indian/Mauritius',
  'Europe/Samara' = 'Europe/Samara',
  'Indian/Reunion' = 'Indian/Reunion',
  'Asia/Tbilisi' = 'Asia/Tbilisi',
  'Asia/Yerevan' = 'Asia/Yerevan',
  'Asia/Kabul' = 'Asia/Kabul',
  'Asia/Aqtau' = 'Asia/Aqtau',
  'Asia/Aqtobe' = 'Asia/Aqtobe',
  'Asia/Ashgabat' = 'Asia/Ashgabat',
  'Asia/Dushanbe' = 'Asia/Dushanbe',
  'Asia/Karachi' = 'Asia/Karachi',
  'Indian/Kerguelen' = 'Indian/Kerguelen',
  'Indian/Maldives' = 'Indian/Maldives',
  'Antarctica/Mawson' = 'Antarctica/Mawson',
  'Asia/Yekaterinburg' = 'Asia/Yekaterinburg',
  'Asia/Tashkent' = 'Asia/Tashkent',
  'Asia/Colombo' = 'Asia/Colombo',
  'Asia/Kolkata' = 'Asia/Kolkata',
  'Asia/Kathmandu' = 'Asia/Kathmandu',
  'Asia/Almaty' = 'Asia/Almaty',
  'Asia/Bishkek' = 'Asia/Bishkek',
  'Indian/Chagos' = 'Indian/Chagos',
  'Asia/Dhaka' = 'Asia/Dhaka',
  'Asia/Omsk' = 'Asia/Omsk',
  'Asia/Thimphu' = 'Asia/Thimphu',
  'Antarctica/Vostok' = 'Antarctica/Vostok',
  'Indian/Cocos' = 'Indian/Cocos',
  'Asia/Yangon' = 'Asia/Yangon',
  'Asia/Bangkok' = 'Asia/Bangkok',
  'Indian/Christmas' = 'Indian/Christmas',
  'Antarctica/Davis' = 'Antarctica/Davis',
  'Asia/Saigon' = 'Asia/Saigon',
  'Asia/Hovd' = 'Asia/Hovd',
  'Asia/Jakarta' = 'Asia/Jakarta',
  'Asia/Krasnoyarsk' = 'Asia/Krasnoyarsk',
  'Asia/Brunei' = 'Asia/Brunei',
  'Asia/Shanghai' = 'Asia/Shanghai',
  'Asia/Choibalsan' = 'Asia/Choibalsan',
  'Asia/Hong_Kong' = 'Asia/Hong_Kong',
  'Asia/Kuala_Lumpur' = 'Asia/Kuala_Lumpur',
  'Asia/Macau' = 'Asia/Macau',
  'Asia/Makassar' = 'Asia/Makassar',
  'Asia/Manila' = 'Asia/Manila',
  'Asia/Irkutsk' = 'Asia/Irkutsk',
  'Asia/Singapore' = 'Asia/Singapore',
  'Asia/Taipei' = 'Asia/Taipei',
  'Asia/Ulaanbaatar' = 'Asia/Ulaanbaatar',
  'Australia/Perth' = 'Australia/Perth',
  'Asia/Pyongyang' = 'Asia/Pyongyang',
  'Asia/Dili' = 'Asia/Dili',
  'Asia/Jayapura' = 'Asia/Jayapura',
  'Asia/Yakutsk' = 'Asia/Yakutsk',
  'Pacific/Palau' = 'Pacific/Palau',
  'Asia/Seoul' = 'Asia/Seoul',
  'Asia/Tokyo' = 'Asia/Tokyo',
  'Australia/Darwin' = 'Australia/Darwin',
  'Antarctica/DumontDUrville' = 'Antarctica/DumontDUrville',
  'Australia/Brisbane' = 'Australia/Brisbane',
  'Pacific/Guam' = 'Pacific/Guam',
  'Asia/Vladivostok' = 'Asia/Vladivostok',
  'Pacific/Port_Moresby' = 'Pacific/Port_Moresby',
  'Pacific/Chuuk' = 'Pacific/Chuuk',
  'Australia/Adelaide' = 'Australia/Adelaide',
  'Antarctica/Casey' = 'Antarctica/Casey',
  'Australia/Hobart' = 'Australia/Hobart',
  'Australia/Sydney' = 'Australia/Sydney',
  'Pacific/Efate' = 'Pacific/Efate',
  'Pacific/Guadalcanal' = 'Pacific/Guadalcanal',
  'Pacific/Kosrae' = 'Pacific/Kosrae',
  'Asia/Magadan' = 'Asia/Magadan',
  'Pacific/Norfolk' = 'Pacific/Norfolk',
  'Pacific/Noumea' = 'Pacific/Noumea',
  'Pacific/Pohnpei' = 'Pacific/Pohnpei',
  'Pacific/Funafuti' = 'Pacific/Funafuti',
  'Pacific/Kwajalein' = 'Pacific/Kwajalein',
  'Pacific/Majuro' = 'Pacific/Majuro',
  'Asia/Kamchatka' = 'Asia/Kamchatka',
  'Pacific/Nauru' = 'Pacific/Nauru',
  'Pacific/Tarawa' = 'Pacific/Tarawa',
  'Pacific/Wake' = 'Pacific/Wake',
  'Pacific/Wallis' = 'Pacific/Wallis',
  'Pacific/Auckland' = 'Pacific/Auckland',
  'Pacific/Enderbury' = 'Pacific/Enderbury',
  'Pacific/Fakaofo' = 'Pacific/Fakaofo',
  'Pacific/Fiji' = 'Pacific/Fiji',
  'Pacific/Tongatapu' = 'Pacific/Tongatapu',
  'Pacific/Apia' = 'Pacific/Apia',
  'Pacific/Kiritimati' = 'Pacific/Kiritimati',
}

export enum Language {
  'fr' = 'fr',
  'ar' = 'ar',
  'en' = 'en',
}

export class UserFilterPayloadOld {
  key: string;
  namespace?: string;
  type: string;
}

export class UserNamespaceFilterPayloadOld {
  key: string;
  namespace: string;
  type: string;
}

export class GetListCountReponse {
  count: number;
}

// ====================

export class UserRequest {
  key: string;
  username: string;
  namespace: string;
  type: string;
  parent?: string;
  abilities?: any[];
}

export class FetchFilter<T> implements PaginationType, KeywordType {
  limit?: number;
  skip?: number;
  keyword?: string;
  filterBy?: T;
}

export class CreatedAtUpdatedAtResponse {
  updatedAt: Date;
  updatedBy?: { key: string; name: string };
  createdBy?: { key: string; name: string };
}

export class FetchMultiple<T> {
  list: T[];
  count: number;
}
